apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-seed
  name: mongo-seed
spec:
  selector:
    matchLabels:
      io.kompose.service: mongo-seed
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-seed
    spec:
      containers:
      - image: imaginarycrane/titanic-seed
        name: mongo-seed
        resources: {}
      restartPolicy: Always
status: {}
